dataset:
  path: "dataset/sequences.json"
  max_seq: 1000
  max_transactions: 20
  max_items: 100

gsp:
  min_supp_norm: 0.3
  log_level: 1

prefixspan:
    min_supp_norm: 0.12
    maxlength: 7

# 'gsp' or 'prefixspan' or 'both
type: 'prefixspan'

output:
  # True or False
  with_profile: True
  out_directory: "output/prefixspan_1000_012"