dataset:
  path: "dataset/sequences.json"
  max_seq: 2000
  max_transactions: 20
  max_items: 100

gsp:
  min_supp_norm: 0.4
  log_level: 1

prefixspan:
    min_supp_norm: 0.12
    maxlength: 7

#type: 'gsp'
type: 'prefixspan'

output:
  out_directory: "output/prefixspan_test"